# Generated by Django 5.0.6 on 2026-02-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_kalendarz', '0002_rename_end_time_event_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
